version: "3"
services:
  web:
    build: .
    environment:
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
